server:
  port: 8080

frontend:
  origin: http://localhost:5173

spring:
  application:
    name:
      multi-typer

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/keyklash
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    user:
      name: admin
      password: admin

  data:
    redis:
      host: host.docker.internal
      port: 6379

logging:
  level:
    com.type: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.security: DEBUG


#logging.level.org.springframework.security=DEBUG