server:
  port: ${SERVER_PORT}

frontend:
  origin: ${FRONTEND_ORIGIN}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true


logging:
  level:
    com.type: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.security: DEBUG
